lgrg<-function(){
   ql=read.csv("quality.csv")
   str(ql)
   ##label(ql)
   #pc<-ql$PoorCare
   table(ql$PoorCare)
   #set.seed(88)
   qd<- sample.split(ql$PoorCare,0.75)
   str(qd)
   qtrn<-subset(ql,qd==T)
   qtst<-subset(ql,qd==F)
   #str(qtrn)
   #print(nrow(qtrn))
   #print(nrow(qtst))
#   print(qtst)
 #  print(qtrn)
#   print(nrow(qtrn))
#   plot(pc~ql$OfficeVisits+ql$Narcotics)
   lr=glm(PoorCare ~ OfficeVisits + Narcotics, data=qtrn, family=binomial)
   print(summary(lr))
   #plot(lr)
   pd<-predict(lr,type="response")
   print(summary(pd))
  str(pd)
   #table(qtrn$PoorCare,pd>0.5)
   #table(qtrn$PoorCare)
   ROCprd = prediction(pd, qtrn$PoorCare)
   ROCprf = performance(ROCprd,"tpr","fpr")
   plot(ROCRperf)
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
#str(pd)
 # class(pd)
  #as.numeric(qtrn$PoorCare)
  #class(qtrn$PoorCare)
   #rocprd <- prediction(pd,qtrn$PoorCare)
 #  plot(rocprd)
  }