stat<- function(){
  wn <- read.csv("wine.csv",header=T,sep=",")  
  names(wn)
  print(class(wn))
  wn1<-wn
  wn<-t(wn)
  ag<-as.numeric(wn[6,1:ncol(wn)])
  pr<-as.numeric(wn[2,1:ncol(wn)])
  plot(ag,pr)
  wn<-t(wn)
  me=mean(wn[2,],na.rm=F)
  class(wn1)
  m1=lm(formula=ag~pr,data=wn1)
  print(m1)
  abline(m1,col="red")
  plot(m1)
  termplot(m1)
  summary(m1)
  ##plot(wn$Age ~ wn$Price)
  ##plot(Age,Price,type="p",data=wn)
}